# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('text', redactor.fields.RedactorField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Race', verbose_name='Týká se rasy')),
            ],
            options={
                'verbose_name': 'Legenda',
                'verbose_name_plural': 'Legendy',
            },
        ),
    ]
