# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jméno')),
                ('surname', models.CharField(max_length=200, verbose_name='Příjmení')),
                ('nick', models.CharField(blank=True, max_length=200, null=True, verbose_name='Přezdívka')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Věk')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('group', models.CharField(blank=True, max_length=200, null=True, verbose_name='Skupina')),
                ('date', models.DateTimeField(verbose_name='Datum registrace')),
                ('ip', models.GenericIPAddressField(verbose_name='IP adresa')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Race', verbose_name='Bojuje za')),
            ],
            options={
                'verbose_name': 'Ragistrovaný hráč',
                'verbose_name_plural': 'Registrovaní hráči',
            },
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('name', 'surname', 'nick')]),
        ),
    ]
