# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Titulek')),
                ('tooltip', models.CharField(max_length=200, verbose_name='Popisek')),
                ('filefield', models.FileField(blank=True, upload_to='', verbose_name='Soubor')),
            ],
            options={
                'verbose_name': 'Soubor',
                'verbose_name_plural': 'Nahrané soubory',
            },
        ),
        migrations.CreateModel(
            name='Harmonogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=200, verbose_name='Program')),
                ('time_start', models.TimeField(verbose_name='Čas začátku')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Čas konce')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Harmonogram',
            },
        ),
        migrations.CreateModel(
            name='MapPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název')),
                ('long', models.CharField(max_length=200, verbose_name='Zeměpisná délka')),
                ('lat', models.CharField(max_length=200, verbose_name='Zeměpisná šířka')),
            ],
            options={
                'verbose_name': 'Bod na mapě',
                'verbose_name_plural': 'Nastavení - Mapa',
            },
        ),
        migrations.CreateModel(
            name='TextOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Předmět')),
                ('identifier', models.CharField(max_length=200, verbose_name='Identifikator')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Nastavení - Text',
                'verbose_name_plural': 'Nastavení - Texty',
            },
        ),
    ]
