# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nadpis')),
                ('text', redactor.fields.RedactorField()),
                ('date', models.DateTimeField(verbose_name='Datum vydání')),
            ],
            options={
                'verbose_name': 'Novinka',
                'verbose_name_plural': 'Novinky',
            },
        ),
    ]
