# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nadpis')),
                ('identifier', models.CharField(max_length=200, verbose_name='Identifikator pro stranku')),
                ('text', redactor.fields.RedactorField()),
            ],
            options={
                'verbose_name': 'Panely a texty všude možně',
                'verbose_name_plural': 'Panely a texty všude možně',
            },
        ),
        migrations.CreateModel(
            name='DateOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Událost')),
                ('identifier', models.CharField(max_length=200, verbose_name='Identifikator')),
                ('date', models.DateTimeField(verbose_name='Datum')),
            ],
            options={
                'verbose_name': 'Nastavení - Datum',
                'verbose_name_plural': 'Nastavení - Data',
            },
        ),
    ]
